In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../dataset/WA_Fn-UseC_-Sales-Win-Loss.csv')

In [3]:
data.head()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,1641984,Exterior Accessories,Car Accessories,Northwest,Fields Sales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1
1,1658010,Exterior Accessories,Car Accessories,Pacific,Reseller,63,Loss,2,163,163,0,3,5,0,Unknown,0.00000,1.000000,0.000000,1
2,1674737,Motorcycle Parts,Performance & Non-auto,Pacific,Reseller,24,Won,7,82,82,7750,1,1,0,Unknown,1.00000,0.000000,0.000000,1
3,1675224,Shelters & RV,Performance & Non-auto,Midwest,Reseller,16,Loss,5,124,124,0,1,1,0,Known,1.00000,0.000000,0.000000,1
4,1689785,Exterior Accessories,Car Accessories,Pacific,Reseller,69,Loss,11,91,13,69756,1,1,0,Unknown,0.00000,0.141125,0.000000,4

In [4]:
data.columns

Index(['Opportunity Number', 'Supplies Subgroup', 'Supplies Group', 'Region',
       'Route To Market', 'Elapsed Days In Sales Stage', 'Opportunity Result',
       'Sales Stage Change Count', 'Total Days Identified Through Closing',
       'Total Days Identified Through Qualified', 'Opportunity Amount USD',
       'Client Size By Revenue', 'Client Size By Employee Count',
       'Revenue From Client Past Two Years', 'Competitor Type',
       'Ratio Days Identified To Total Days',
       'Ratio Days Validated To Total Days',
       'Ratio Days Qualified To Total Days', 'Deal Size Category'],
      dtype='object')

In [5]:
ord(" ")

32

In [6]:
chr(32)

' '

In [7]:
aa = 'Opportunity Number'

In [8]:
aa.replace(chr(32),'')

'OpportunityNumber'

In [9]:

for i in data.columns:
    data.rename(columns={i:i.replace(chr(32),'')},inplace=True)

In [10]:
data.columns

Index(['OpportunityNumber', 'SuppliesSubgroup', 'SuppliesGroup', 'Region',
       'RouteToMarket', 'ElapsedDaysInSalesStage', 'OpportunityResult',
       'SalesStageChangeCount', 'TotalDaysIdentifiedThroughClosing',
       'TotalDaysIdentifiedThroughQualified', 'OpportunityAmountUSD',
       'ClientSizeByRevenue', 'ClientSizeByEmployeeCount',
       'RevenueFromClientPastTwoYears', 'CompetitorType',
       'RatioDaysIdentifiedToTotalDays', 'RatioDaysValidatedToTotalDays',
       'RatioDaysQualifiedToTotalDays', 'DealSizeCategory'],
      dtype='object')

In [11]:
data.head(1)

,OpportunityNumber,SuppliesSubgroup,SuppliesGroup,Region,RouteToMarket,ElapsedDaysInSalesStage,OpportunityResult,SalesStageChangeCount,TotalDaysIdentifiedThroughClosing,TotalDaysIdentifiedThroughQualified,OpportunityAmountUSD,ClientSizeByRevenue,ClientSizeByEmployeeCount,RevenueFromClientPastTwoYears,CompetitorType,RatioDaysIdentifiedToTotalDays,RatioDaysValidatedToTotalDays,RatioDaysQualifiedToTotalDays,DealSizeCategory
0,1641984,Exterior Accessories,Car Accessories,Northwest,Fields Sales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1

In [12]:
data.drop_duplicates#78025

<bound method DataFrame.drop_duplicates of        OpportunityNumber         SuppliesSubgroup           SuppliesGroup  \
0                1641984     Exterior Accessories         Car Accessories
1                1658010     Exterior Accessories         Car Accessories
2                1674737         Motorcycle Parts  Performance & Non-auto
3                1675224            Shelters & RV  Performance & Non-auto
4                1689785     Exterior Accessories         Car Accessories
5                1692390            Shelters & RV  Performance & Non-auto
6                1935837        Garage & Car Care         Car Accessories
7                1952571     Exterior Accessories         Car Accessories
8                1999486  Batteries & Accessories         Car Accessories
9                2052337     Exterior Accessories         Car Accessories
10               2100568     Exterior Accessories         Car Accessories
11               2190367        Garage & Car Care         Car Accessories
12               2217068        Performance Parts  Performance & Non-auto
13               2223143     Exterior Accessories         Car Accessories
14               2228661  Batteries & Accessories         Car Accessories
15               2228983  Batteries & Accessories         Car Accessories
16               2263363         Towing & Hitches         Car Accessories
17               2277276        Garage & Car Care         Car Accessories
18               2280685            Shelters & RV  Performance & Non-auto
19               2284303            Shelters & RV  Performance & Non-auto
20               2289905            Shelters & RV  Performance & Non-auto
21               2292996            Shelters & RV  Performance & Non-auto
22               2296022     Exterior Accessories         Car Accessories
23               2315483         Motorcycle Parts  Performance & Non-auto
24               2315706         Motorcycle Parts  Performance & Non-auto
25               2315732         Motorcycle Parts  Performance & Non-auto
26               2345802         Motorcycle Parts  Performance & Non-auto
27               2368166        Replacement Parts         Car Accessories
28               3255657            Shelters & RV  Performance & Non-auto
29               3256426        Replacement Parts         Car Accessories
...                  ...                      ...                     ...
77995           10068733            Shelters & RV  Performance & Non-auto
77996           10069059        Replacement Parts         Car Accessories
77997           10070563         Motorcycle Parts  Performance & Non-auto
77998           10071260         Motorcycle Parts  Performance & Non-auto
77999           10072716            Shelters & RV  Performance & Non-auto
78000           10072791         Towing & Hitches         Car Accessories
78001           10072868        Performance Parts  Performance & Non-auto
78002           10073020     Exterior Accessories         Car Accessories
78003           10073387         Motorcycle Parts  Performance & Non-auto
78004           10073827         Motorcycle Parts  Performance & Non-auto
78005           10076730            Shelters & RV  Performance & Non-auto
78006           10076856        Replacement Parts         Car Accessories
78007           10077716        Replacement Parts         Car Accessories
78008           10078223         Motorcycle Parts  Performance & Non-auto
78009           10079844  Batteries & Accessories         Car Accessories
78010           10079993     Interior Accessories         Car Accessories
78011           10081096        Replacement Parts         Car Accessories
78012           10081102     Exterior Accessories         Car Accessories
78013           10081854        Garage & Car Care         Car Accessories
78014           10082531         Motorcycle Parts  Performance & Non-auto
78015           10083432         Motorcycle Parts  Performance & Non-auto
78016           10085039     Interior Accessories         Car Accessories
78017           10085764        Garage & Car Care         Car Accessories
78018           10086420  Batteries & Accessories         Car Accessories
78019           10089917        Garage & Car Care         Car Accessories
78020           10089932  Batteries & Accessories         Car Accessories
78021           10089961            Shelters & RV  Performance & Non-auto
78022           10090145     Exterior Accessories         Car Accessories
78023           10090430     Exterior Accessories         Car Accessories
78024           10094255     Interior Accessories         Car Accessories

             Region RouteToMarket  ElapsedDaysInSalesStage OpportunityResult  \
0         Northwest  Fields Sales                       76               Won
1           Pacific      Reseller                       63              Loss
2           Pacific      Reseller                       24               Won
3           Midwest      Reseller                       16              Loss
4           Pacific      Reseller                       69              Loss
5           Pacific      Reseller                       89              Loss
6           Pacific  Fields Sales                      111               Won
7           Pacific  Fields Sales                       82              Loss
8         Northwest  Fields Sales                       68              Loss
9           Pacific      Reseller                       18              Loss
10        Northwest  Fields Sales                       76              Loss
11          Midwest  Fields Sales                       87              Loss
12          Midwest      Reseller                       35              Loss
13          Pacific      Reseller                       16              Loss
14          Midwest  Fields Sales                       81              Loss
15        Northwest  Fields Sales                       79               Won
16          Midwest      Reseller                       83              Loss
17          Pacific  Fields Sales                       65              Loss
18        Northwest  Fields Sales                       91              Loss
19        Northwest  Fields Sales                       65              Loss
20          Pacific  Fields Sales                       89              Loss
21          Midwest      Reseller                       62              Loss
22          Midwest      Reseller                       16              Loss
23          Midwest  Fields Sales                       83              Loss
24        Northwest      Reseller                       73               Won
25          Midwest      Reseller                       76              Loss
26          Midwest  Fields Sales                       86              Loss
27        Northwest  Fields Sales                       60              Loss
28        Northwest  Fields Sales                       72              Loss
29        Northwest  Fields Sales                       44              Loss
...             ...           ...                      ...               ...
77995     Northeast      Reseller                        1              Loss
77996  Mid-Atlantic      Reseller                        0               Won
77997     Southeast  Fields Sales                        0               Won
77998     Southeast  Fields Sales                        1              Loss
77999  Mid-Atlantic      Reseller                        0              Loss
78000     Northeast      Reseller                        0              Loss
78001     Southwest      Reseller                        0               Won
78002  Mid-Atlantic      Reseller                        1              Loss
78003     Northeast  Fields Sales                        1               Won
78004     Northeast  Fields Sales                        1               Won
78005     Southwest  Fields Sales                        1              Loss
78006     Southeast  Fields Sales                        1               Won
78007  Mid-Atlantic  Fields Sales                        0              Loss
78008     Southeast      Reseller                        0               Won
78009     Southeast  Fields Sales                        0              Loss
78010     Southwest  Fields Sales                        0              Loss
78011     Southeast      Reseller                        0               Won
78012     Southeast  Fields Sales                        0               Won
78013     Northeast  Fields Sales                        0               Won
78014     Southeast      Reseller                        0               Won
78015     Southwest  Fields Sales                        0              Loss
78016     Southeast      Reseller                        0               Won
78017  Mid-Atlantic      Reseller                        0               Won
78018     Southwest      Reseller                        0               Won
78019     Southeast      Reseller                        0               Won
78020     Southeast      Reseller                        0              Loss
78021     Northeast      Reseller                        0               Won
78022     Southeast      Reseller                        0              Loss
78023     Southeast  Fields Sales                        0              Loss
78024  Mid-Atlantic      Reseller                        0              Loss

       SalesStageChangeCount  TotalDaysIdentifiedThroughClosing  \
0                         13                                104
1                          2                                163
2                          7                                 82
3                          5                                124
4                         11                                 91
5                          3                                114
6                         12                                112
7                          6                                 70
8                          8                                156
9                          7                                 50
10                         8                                165
11                         5                                142
12                         6                                 31
13                         5                                208
14                        10                                138
15                         5                                 32
16                        13                                130
17                        17                                150
18                         6                                103
19                        13                                125
20                         7                                 60
21                        14                                 88
22                         8                                169
23                         7                                 90
24                         9                                127
25                         8                                133
26                         2                                119
27                         8                                101
28                         9                                123
29                         4                                  9
...                      ...                                ...
77995                      2                                  0
77996                      3                                  1
77997                      3                                  1
77998                      1                                  0
77999                      3                                  1
78000                      3                                  1
78001                      2                                  0
78002                      2                                  0
78003                      2                                  0
78004                      2                                  0
78005                      2                                  0
78006                      1                                  0
78007                      2                                  0
78008                      2                                  0
78009                      1                                  0
78010                      1                                  0
78011                      2                                  0
78012                      2                                  0
78013                      1                                  0
78014                      1                                  0
78015                      1                                  0
78016                      1                                  0
78017                      1                                  0
78018                      1                                  0
78019                      1                                  0
78020                      2                                  0
78021                      1                                  0
78022                      2                                  0
78023                      2                                  0
78024                      1                                  0

       TotalDaysIdentifiedThroughQualified  OpportunityAmountUSD  \
0                                      101                     0
1                                      163                     0
2                                       82                  7750
3                                      124                     0
4                                       13                 69756
5                                        0                232522
6                                      112                 20001
7                                       70                450000
8                                      156                250000
9                                       50                 55003
10                                     165                     0
11                                     142                400000
12                                      31                 10000
13                                     208                232522
14                                     138                200000
15                                      32                     0
16                                     130                 60000
17                                     150                250009
18                                     103                500000
19                                     125                100000
20                                      60                150000
21                                      87                210000
22                                     169                  3000
23                                      48                 80000
24                                     127                 40721
25                                     133                 64000
26                                     119                 51000
27                                     101                 50000
28                                     123                500000
29                                       9                 35812
...                                    ...                   ...
77995                                    0                150000
77996                                    1                 94945
77997                                    1                 19014
77998                                    0                 30000
77999                                    1                 18000
78000                                    1                150000
78001                                    0                 95000
78002                                    0                 56363
78003                                    0                    68
78004                                    0                    45
78005                                    0                200000
78006                                    0                  1700
78007                                    0                 90000
78008                                    0                 17000
78009                                    0                100000
78010                                    0                   100
78011                                    0                 40000
78012                                    0                 59000
78013                                    0                 17000
78014                                    0                 12000
78015                                    0                   291
78016                                    0                  5376
78017                                    0                 57982
78018                                    0                 18000
78019                                    0                 22000
78020                                    0                250000
78021                                    0                180000
78022                                    0                 90000
78023                                    0                120000
78024                                    0                 90000

       ClientSizeByRevenue  ClientSizeByEmployeeCount  \
0                        5                          5
1                        3                          5
2                        1                          1
3                        1                          1
4                        1                          1
5                        5                          1
6                        4                          5
7                        1                          1
8                        1                          5
9                        1                          1
10                       1                          2
11                       5                          5
12                       2                          1
13                       1                          1
14                       4                          5
15                       5                          1
16                       4                          3
17                       5                          5
18                       1                          3
19                       1                          5
20                       5                          4
21                       5                          3
22                       3                          2
23                       3                          5
24                       1                          1
25                       1                          4
26                       1                          3
27                       5                          3
28                       1                          5
29                       1                          3
...                    ...                        ...
77995                    1                          1
77996                    1                          1
77997                    1                          1
77998                    1                          1
77999                    1                          1
78000                    1                          1
78001                    1                          1
78002                    1                          1
78003                    1                          1
78004                    1                          1
78005                    1                          1
78006                    1                          1
78007                    1                          1
78008                    1                          1
78009                    1                          1

In [ ]:
data[data['Region']=='Southwest']

In [ ]:
# fail
# data['SuppliesGroup'] = np.where(data['SuppliesGroup'].str.contains(chr(32)) == True, data['SuppliesGroup'].replace(chr(32),''),data['SuppliesGroup'])

In [11]:
data['SuppliesSubgroup'] = np.where(data['SuppliesSubgroup'].str.contains(chr(32)) == True, \
                                    data['SuppliesSubgroup'].str.replace(chr(32),''),\
                                    data['SuppliesSubgroup'])

In [12]:
data['SuppliesGroup'] = np.where(data['SuppliesGroup'].str.contains(chr(32)) == True, \
                                 data['SuppliesGroup'].str.replace(chr(32),''),\
                                 data['SuppliesGroup'])

In [13]:
data['RouteToMarket'] = np.where(data['RouteToMarket'].str.contains(chr(32)) == True, \
                                 data['RouteToMarket'].str.replace(chr(32),''),\
                                 data['RouteToMarket'])

In [16]:
data.head()

,OpportunityNumber,SuppliesSubgroup,SuppliesGroup,Region,RouteToMarket,ElapsedDaysInSalesStage,OpportunityResult,SalesStageChangeCount,TotalDaysIdentifiedThroughClosing,TotalDaysIdentifiedThroughQualified,OpportunityAmountUSD,ClientSizeByRevenue,ClientSizeByEmployeeCount,RevenueFromClientPastTwoYears,CompetitorType,RatioDaysIdentifiedToTotalDays,RatioDaysValidatedToTotalDays,RatioDaysQualifiedToTotalDays,DealSizeCategory
0,1641984,ExteriorAccessories,CarAccessories,Northwest,FieldsSales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1
1,1658010,ExteriorAccessories,CarAccessories,Pacific,Reseller,63,Loss,2,163,163,0,3,5,0,Unknown,0.00000,1.000000,0.000000,1
2,1674737,MotorcycleParts,Performance&Non-auto,Pacific,Reseller,24,Won,7,82,82,7750,1,1,0,Unknown,1.00000,0.000000,0.000000,1
3,1675224,Shelters&RV,Performance&Non-auto,Midwest,Reseller,16,Loss,5,124,124,0,1,1,0,Known,1.00000,0.000000,0.000000,1
4,1689785,ExteriorAccessories,CarAccessories,Pacific,Reseller,69,Loss,11,91,13,69756,1,1,0,Unknown,0.00000,0.141125,0.000000,4

#### fail

In [ ]:
data.loc[2,'RouteToMarket']

In [ ]:
data.loc[0,'RouteToMarket'].find(chr(32))>0

In [ ]:
data.loc[0,'RouteToMarket'].replace(chr(32),'')

In [ ]:
for i in range (0,len(data['RouteToMarket'])):
    if data.loc[i,'RouteToMarket'].find(chr(32))>0:
        data.loc[i,'RouteToMarket'] = data.loc[i,'RouteToMarket'].replace(chr(32),'')

#### 라벨링

In [14]:
data.columns

Index(['OpportunityNumber', 'SuppliesSubgroup', 'SuppliesGroup', 'Region',
       'RouteToMarket', 'ElapsedDaysInSalesStage', 'OpportunityResult',
       'SalesStageChangeCount', 'TotalDaysIdentifiedThroughClosing',
       'TotalDaysIdentifiedThroughQualified', 'OpportunityAmountUSD',
       'ClientSizeByRevenue', 'ClientSizeByEmployeeCount',
       'RevenueFromClientPastTwoYears', 'CompetitorType',
       'RatioDaysIdentifiedToTotalDays', 'RatioDaysValidatedToTotalDays',
       'RatioDaysQualifiedToTotalDays', 'DealSizeCategory'],
      dtype='object')

In [15]:
from sklearn.preprocessing import LabelEncoder


le_SuppliesSubgroup = LabelEncoder()
le_SuppliesGroup = LabelEncoder()
le_RouteToMarket = LabelEncoder()
le_CompetitorType = LabelEncoder()
# 여러 아이템들 모두 라벨링 해주는

data['SuppliesSubgroup'] =le_SuppliesSubgroup.fit_transform(data.SuppliesSubgroup)
data['SuppliesGroup'] = le_SuppliesGroup.fit_transform(data.SuppliesGroup)
data['RouteToMarket'] = le_RouteToMarket.fit_transform(data.RouteToMarket)
data['CompetitorType'] = le_CompetitorType.fit_transform(data.CompetitorType)

In [19]:
data.head()

,OpportunityNumber,SuppliesSubgroup,SuppliesGroup,Region,RouteToMarket,ElapsedDaysInSalesStage,OpportunityResult,SalesStageChangeCount,TotalDaysIdentifiedThroughClosing,TotalDaysIdentifiedThroughQualified,OpportunityAmountUSD,ClientSizeByRevenue,ClientSizeByEmployeeCount,RevenueFromClientPastTwoYears,CompetitorType,RatioDaysIdentifiedToTotalDays,RatioDaysValidatedToTotalDays,RatioDaysQualifiedToTotalDays,DealSizeCategory
0,1641984,2,0,Northwest,0,76,Won,13,104,101,0,5,5,0,2,0.69636,0.113985,0.154215,1
1,1658010,2,0,Pacific,2,63,Loss,2,163,163,0,3,5,0,2,0.00000,1.000000,0.000000,1
2,1674737,5,2,Pacific,2,24,Won,7,82,82,7750,1,1,0,2,1.00000,0.000000,0.000000,1
3,1675224,8,2,Midwest,2,16,Loss,5,124,124,0,1,1,0,0,1.00000,0.000000,0.000000,1
4,1689785,2,0,Pacific,2,69,Loss,11,91,13,69756,1,1,0,2,0.00000,0.141125,0.000000,4

#### 지역별 그룹

In [33]:
data.corr() #No OpportunityResult

,OpportunityNumber,SuppliesSubgroup,SuppliesGroup,Region,RouteToMarket,ElapsedDaysInSalesStage,SalesStageChangeCount,TotalDaysIdentifiedThroughClosing,TotalDaysIdentifiedThroughQualified,OpportunityAmountUSD,ClientSizeByRevenue,ClientSizeByEmployeeCount,RevenueFromClientPastTwoYears,CompetitorType,RatioDaysIdentifiedToTotalDays,RatioDaysValidatedToTotalDays,RatioDaysQualifiedToTotalDays,DealSizeCategory
OpportunityNumber,1.000000,0.010070,0.018497,0.029258,0.025989,-0.765023,-0.253709,-0.446296,-0.435849,-0.015264,-0.404433,-0.405896,0.033263,0.143552,0.002194,-0.057203,-0.048271,-0.042416
SuppliesSubgroup,0.010070,1.000000,0.483989,0.013601,-0.084233,-0.021305,0.012089,0.029116,0.029009,0.042687,0.007608,0.004495,-0.023028,-0.026331,0.037759,-0.007571,-0.014806,0.067895
SuppliesGroup,0.018497,0.483989,1.000000,0.018759,-0.040531,-0.024042,-0.012416,0.036692,0.037400,0.047963,0.004754,-0.000878,-0.028676,-0.011122,0.005008,0.006947,-0.035719,0.075018
Region,0.029258,0.013601,0.018759,1.000000,0.002974,-0.032023,0.003836,0.006100,0.005067,0.041350,-0.051827,-0.096876,-0.041270,0.017259,0.011693,-0.046662,0.030619,0.041498
RouteToMarket,0.025989,-0.084233,-0.040531,0.002974,1.000000,-0.092562,0.037420,0.005770,0.003910,-0.244144,-0.114581,-0.115546,-0.084054,0.226518,-0.202843,0.160147,-0.038971,-0.306558
ElapsedDaysInSalesStage,-0.765023,-0.021305,-0.024042,-0.032023,-0.092562,1.000000,-0.025329,-0.022162,-0.022879,-0.013481,0.380462,0.375500,-0.017862,-0.119747,-0.018411,0.015332,0.020342,-0.008166
SalesStageChangeCount,-0.253709,0.012089,-0.012416,0.003836,0.037420,-0.025329,1.000000,0.380387,0.355711,0.050513,0.113476,0.126367,0.055813,-0.163058,-0.067853,-0.013195,0.280643,0.066174
TotalDaysIdentifiedThroughClosing,-0.446296,0.029116,0.036692,0.006100,0.005770,-0.022162,0.380387,1.000000,0.983665,0.077330,0.159945,0.169517,-0.048659,-0.089392,0.092619,0.124961,0.026621,0.142835
TotalDaysIdentifiedThroughQualified,-0.435849,0.029009,0.037400,0.005067,0.003910,-0.022879,0.355711,0.983665,1.000000,0.078204,0.156334,0.165221,-0.056061,-0.086468,0.104883,0.145948,0.028195,0.146495
OpportunityAmountUSD,-0.015264,0.042687,0.047963,0.041350,-0.244144,-0.013481,0.050513,0.077330,0.078204,1.000000,0.062045,0.054670,0.097925,-0.130270,0.067238,-0.051389,0.046593,0.763637
ClientSizeByRevenue,-0.404433,0.007608,0.004754,-0.051827,-0.114581,0.380462,0.113476,0.159945,0.156334,0.062045,1.000000,0.525398,0.036175,-0.122749,0.024396,-0.004273,0.035758,0.087255
ClientSizeByEmployeeCount,-0.405896,0.004495,-0.000878,-0.096876,-0.115546,0.375500,0.126367,0.169517,0.165221,0.054670,0.525398,1.000000,0.029480,-0.126326,0.022063,-0.004636,0.040988,0.088753
RevenueFromClientPastTwoYears,0.033263,-0.023028,-0.028676,-0.041270,-0.084054,-0.017862,0.055813,-0.048659,-0.056061,0.097925,0.036175,0.029480,1.000000,-0.059017,-0.048011,-0.083851,0.125188,0.074210
CompetitorType,0.143552,-0.026331,-0.011122,0.017259,0.226518,-0.119747,-0.163058,-0.089392,-0.086468,-0.130270,-0.122749,-0.126326,-0.059017,1.000000,0.057954,0.002399,-0.147884,-0.147978
RatioDaysIdentifiedToTotalDays,0.002194,0.037759,0.005008,0.011693,-0.202843,-0.018411,-0.067853,0.092619,0.104883,0.067238,0.024396,0.022063,-0.048011,0.057954,1.000000,-0.476212,-0.250435,0.125693
RatioDaysValidatedToTotalDays,-0.057203,-0.007571,0.006947,-0.046662,0.160147,0.015332,-0.013195,0.124961,0.145948,-0.051389,-0.004273,-0.004636,-0.083851,0.002399,-0.476212,1.000000,-0.434734,-0.045212
RatioDaysQualifiedToTotalDays,-0.048271,-0.014806,-0.035719,0.030619,-0.038971,0.020342,0.280643,0.026621,0.028195,0.046593,0.035758,0.040988,0.125188,-0.147884,-0.250435,-0.434734,1.000000,0.029038
DealSizeCategory,-0.042416,0.067895,0.075018,0.041498,-0.306558,-0.008166,0.066174,0.142835,0.146495,0.763637,0.087255,0.088753,0.074210,-0.147978,0.125693,-0.045212,0.029038,1.000000

In [34]:
sortKey = ['OpportunityNumber', 'SuppliesSubgroup', 'SuppliesGroup', 'Region']

In [35]:
sortedDf = data.sort_values(sortKey).reset_index(drop=True)

In [36]:
sortedDf.head()

,OpportunityNumber,SuppliesSubgroup,SuppliesGroup,Region,RouteToMarket,ElapsedDaysInSalesStage,OpportunityResult,SalesStageChangeCount,TotalDaysIdentifiedThroughClosing,TotalDaysIdentifiedThroughQualified,OpportunityAmountUSD,ClientSizeByRevenue,ClientSizeByEmployeeCount,RevenueFromClientPastTwoYears,CompetitorType,RatioDaysIdentifiedToTotalDays,RatioDaysValidatedToTotalDays,RatioDaysQualifiedToTotalDays,DealSizeCategory
0,1641984,2,0,3,0,76,Won,13,104,101,0,5,5,0,2,0.69636,0.113985,0.154215,1
1,1658010,2,0,4,2,63,Loss,2,163,163,0,3,5,0,2,0.00000,1.000000,0.000000,1
2,1674737,5,2,4,2,24,Won,7,82,82,7750,1,1,0,2,1.00000,0.000000,0.000000,1
3,1675224,8,2,1,2,16,Loss,5,124,124,0,1,1,0,0,1.00000,0.000000,0.000000,1
4,1689785,2,0,4,2,69,Loss,11,91,13,69756,1,1,0,2,0.00000,0.141125,0.000000,4

In [37]:
groupKey=[ 'Region']

In [38]:
groupDf =  sortedDf.groupby(groupKey)

In [39]:
groupDf

In [40]:
oneGroup = groupDf.get_group(list(groupDf.groups)[1])

In [41]:
oneGroup.head()

,OpportunityNumber,SuppliesSubgroup,SuppliesGroup,Region,RouteToMarket,ElapsedDaysInSalesStage,OpportunityResult,SalesStageChangeCount,TotalDaysIdentifiedThroughClosing,TotalDaysIdentifiedThroughQualified,OpportunityAmountUSD,ClientSizeByRevenue,ClientSizeByEmployeeCount,RevenueFromClientPastTwoYears,CompetitorType,RatioDaysIdentifiedToTotalDays,RatioDaysValidatedToTotalDays,RatioDaysQualifiedToTotalDays,DealSizeCategory
3,1675224,8,2,1,2,16,Loss,5,124,124,0,1,1,0,0,1.000000,0.000000,0.000000,1
17,2190367,3,0,1,0,87,Loss,5,142,142,400000,5,5,0,0,0.015482,0.370162,0.614356,6
20,2217068,6,2,1,2,35,Loss,6,31,31,10000,2,1,0,2,0.000000,0.167213,0.832787,2
23,2228661,0,0,1,0,81,Loss,10,138,138,200000,4,5,4,0,0.000000,0.730044,0.269956,5
25,2263363,10,0,1,2,83,Loss,13,130,130,60000,4,3,0,2,0.121820,0.558982,0.319198,4

In [42]:
from sklearn.model_selection import train_test_split#파이썬만 가진

In [43]:
oneGroup.columns

Index(['OpportunityNumber', 'SuppliesSubgroup', 'SuppliesGroup', 'Region',
       'RouteToMarket', 'ElapsedDaysInSalesStage', 'OpportunityResult',
       'SalesStageChangeCount', 'TotalDaysIdentifiedThroughClosing',
       'TotalDaysIdentifiedThroughQualified', 'OpportunityAmountUSD',
       'ClientSizeByRevenue', 'ClientSizeByEmployeeCount',
       'RevenueFromClientPastTwoYears', 'CompetitorType',
       'RatioDaysIdentifiedToTotalDays', 'RatioDaysValidatedToTotalDays',
       'RatioDaysQualifiedToTotalDays', 'DealSizeCategory'],
      dtype='object')

In [44]:
features = ['OpportunityNumber','SuppliesSubgroup', 'SuppliesGroup','RouteToMarket', 'ElapsedDaysInSalesStage',\
           'SalesStageChangeCount', 'TotalDaysIdentifiedThroughClosing','TotalDaysIdentifiedThroughQualified', 'OpportunityAmountUSD',\
           'ClientSizeByRevenue', 'ClientSizeByEmployeeCount','RevenueFromClientPastTwoYears', 'CompetitorType',\
           'RatioDaysIdentifiedToTotalDays', 'RatioDaysValidatedToTotalDays','RatioDaysQualifiedToTotalDays', 'DealSizeCategory']
label = ['OpportunityResult']

In [45]:
len(data) # !=77829 : OpportunityNumber not uk

78025

In [46]:
trainingData_features,\
testData_features,\
trainingData_label,\
testData_label= train_test_split(oneGroup[features],
                oneGroup[label],
                test_size = 0.3, 
                 random_state = 3)
# array : 내 데이터 / test_size: default 0.25 / random_state : 고정하면 재현 가능,정수만 가능 / shuffle 기존 데이터 섞고 랜덤으로 뽑는
# rows가 14000개 6000개 분리된 -> 총4개로

#### 4. 모델 선언

In [47]:
from sklearn import svm

In [49]:
model_method = svm.SVC()

In [50]:
model = model_method.fit(trainingData_features,
                        trainingData_label)#문제지와 답지 학습

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

#### 5. 훈련 (훈련데이터의 feature, label 활용)

In [51]:
predict = model.predict(testData_features)
predict

array(['Loss', 'Loss', 'Loss', ..., 'Loss', 'Loss', 'Loss'], dtype=object)

In [52]:
testData_features2 = testData_features.reset_index(drop=True)

testData_label2 = testData_label.reset_index(drop=True)

finalResult = pd.concat(\
                       [testData_features2,testData_label2],\
                       axis=1)

finalResult['PREDICT'] = predict

In [53]:
finalResult[finalResult['PREDICT']=='Won']

,OpportunityNumber,SuppliesSubgroup,SuppliesGroup,RouteToMarket,ElapsedDaysInSalesStage,SalesStageChangeCount,TotalDaysIdentifiedThroughClosing,TotalDaysIdentifiedThroughQualified,OpportunityAmountUSD,ClientSizeByRevenue,ClientSizeByEmployeeCount,RevenueFromClientPastTwoYears,CompetitorType,RatioDaysIdentifiedToTotalDays,RatioDaysValidatedToTotalDays,RatioDaysQualifiedToTotalDays,DealSizeCategory,OpportunityResult,PREDICT
3439,9627317,5,2,2,12,2,5,5,25000,1,1,0,2,0.000000,1.000000,0.0,3,Won,Won
4393,8135025,3,0,2,39,3,3,3,4900,1,1,0,2,0.266667,0.733333,0.0,1,Won,Won
5961,9877355,3,0,2,5,2,4,4,1248,1,1,0,0,1.000000,0.000000,0.0,1,Won,Won

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [54]:
ac_score = accuracy_score(finalResult.OpportunityResult,finalResult.PREDICT)

In [55]:
ac_score

0.7492863939105614

In [56]:
cl_report = classification_report(finalResult.OpportunityResult,finalResult.PREDICT)

In [57]:
print("result = \n",cl_report)

result =
               precision    recall  f1-score   support

        Loss       0.75      1.00      0.86      4722
         Won       1.00      0.00      0.00      1584

    accuracy                           0.75      6306
   macro avg       0.87      0.50      0.43      6306
weighted avg       0.81      0.75      0.64      6306

#### def

In [58]:
def test_classification(oneGroup):
    oneGroup = groupDf.get_group(list(groupDf.groups)[1])
    eachGroup = oneGroup.reset_index(drop=True)

    from sklearn.model_selection import train_test_split

    features = ['OpportunityNumber','SuppliesSubgroup', 'SuppliesGroup','RouteToMarket', 'ElapsedDaysInSalesStage',\
               'SalesStageChangeCount', 'TotalDaysIdentifiedThroughClosing','TotalDaysIdentifiedThroughQualified', 'OpportunityAmountUSD',\
               'ClientSizeByRevenue', 'ClientSizeByEmployeeCount','RevenueFromClientPastTwoYears', 'CompetitorType',\
               'RatioDaysIdentifiedToTotalDays', 'RatioDaysValidatedToTotalDays','RatioDaysQualifiedToTotalDays', 'DealSizeCategory']
    label = ['OpportunityResult']

    trainingData_features,\
    testData_features,\
    trainingData_label,\
    testData_label= train_test_split(eachGroup[features],
                    eachGroup[label],
                    test_size = 0.3, 
                     random_state = 3)

    from sklearn import svm

    model_method = svm.SVC() #정확도 높게 나오는거 c...로 어떻게?

    model = model_method.fit(trainingData_features,
                            trainingData_label)#학습

    predict = model.predict(testData_features)
    predict

    testData_features2 = testData_features.reset_index(drop=True)

    testData_label2 = testData_label.reset_index(drop=True)

    finalResult = pd.concat(\
                           [testData_features2,testData_label2],\
                           axis=1)

    finalResult['PREDICT'] = predict
    
    return finalResult

In [37]:
groupKey=[ 'Region']

In [59]:
testResult = data.groupby(groupKey).apply(test_classification)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [70]:
testResult.head()

          OpportunityNumber  SuppliesSubgroup  SuppliesGroup  RouteToMarket  \
Region
0      0           10062807                 2              0              2
       1            8138992                 4              0              0
       2            8009263                 0              0              4
       3           10030184                 7              0              0
       4            7482076                 1              1              0

          ElapsedDaysInSalesStage  SalesStageChangeCount  \
Region
0      0                        1                      1
       1                       16                      2
       2                       40                      2
       3                        2                      1
       4                       51                      4

          TotalDaysIdentifiedThroughClosing  \
Region
0      0                                  0
       1                                 25
       2                                  7
       3                                  0
       4                                 10

          TotalDaysIdentifiedThroughQualified  OpportunityAmountUSD  \
Region
0      0                                    0                  6008
       1                                   25                125000
       2                                    7                     0
       3                                    0                     6
       4                                    9                     2

          ClientSizeByRevenue  ClientSizeByEmployeeCount  \
Region
0      0                    1                          1
       1                    1                          1
       2                    1                          1
       3                    1                          1
       4                    1                          4

          RevenueFromClientPastTwoYears  CompetitorType  \
Region
0      0                              0               2
       1                              0               0
       2                              0               2
       3                              0               2
       4                              0               0

          RatioDaysIdentifiedToTotalDays  RatioDaysValidatedToTotalDays  \
Region
0      0                             0.0                            0.0
       1                             1.0                            0.0
       2                             0.0                            1.0
       3                             0.0                            0.0
       4                             0.0                            0.0

          RatioDaysQualifiedToTotalDays  DealSizeCategory OpportunityResult  \
Region
0      0                       0.000000                 1               Won
       1                       0.000000                 5              Loss
       2                       0.000000                 1              Loss
       3                       0.000000                 1              Loss
       4                       0.930693                 1               Won

         PREDICT
Region
0      0    Loss
       1    Loss
       2    Loss
       3    Loss
       4    Loss

In [27]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [64]:
as_score = accuracy_score(testResult.OpportunityResult,testResult.PREDICT)

In [65]:
as_score

0.7492863939105614

In [66]:
clfc_report = classification_report(testResult.OpportunityResult,testResult.PREDICT)

In [67]:
print("result= \n",clfc_report)

result=
               precision    recall  f1-score   support

        Loss       0.75      1.00      0.86     33054
         Won       1.00      0.00      0.00     11088

    accuracy                           0.75     44142
   macro avg       0.87      0.50      0.43     44142
weighted avg       0.81      0.75      0.64     44142

## no group

In [ ]:
data.head(1)

In [16]:
le_Region = LabelEncoder()
data['Region'] = le_CompetitorType.fit_transform(data.Region)

In [17]:
features = ['OpportunityNumber','SuppliesSubgroup', 'SuppliesGroup','Region','RouteToMarket','ElapsedDaysInSalesStage',\
           'SalesStageChangeCount', 'TotalDaysIdentifiedThroughClosing','TotalDaysIdentifiedThroughQualified', 'OpportunityAmountUSD',\
           'ClientSizeByRevenue', 'ClientSizeByEmployeeCount','RevenueFromClientPastTwoYears', 'CompetitorType',\
           'RatioDaysIdentifiedToTotalDays', 'RatioDaysValidatedToTotalDays','RatioDaysQualifiedToTotalDays', 'DealSizeCategory']
label = ['OpportunityResult']

In [18]:
from sklearn.model_selection import train_test_split#파이썬만 가진

In [19]:
trainingData_features,\
testData_features,\
trainingData_label,\
testData_label= train_test_split(data[features],
                data[label],
                test_size = 0.3, 
                random_state = 3)
# array : 내 데이터 / test_size: default 0.25 / random_state : 고정하면 재현 가능,정수만 가능 / shuffle 기존 데이터 섞고 랜덤으로 뽑는
# rows가 14000개 6000개 분리된 -> 총4개로

In [20]:
from sklearn import svm

model_method = svm.SVC()

In [21]:
model = model_method.fit(trainingData_features,
                        trainingData_label)#문제지와 답지 학습

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [22]:
predict = model.predict(testData_features)
predict

array(['Loss', 'Loss', 'Loss', ..., 'Loss', 'Loss', 'Loss'], dtype=object)

In [23]:
testData_features2 = testData_features.reset_index(drop=True)

testData_label2 = testData_label.reset_index(drop=True)

finalResult = pd.concat(\
                       [testData_features2,testData_label2],\
                       axis=1)

finalResult['PREDICT'] = predict

In [24]:
finalResult

,OpportunityNumber,SuppliesSubgroup,SuppliesGroup,Region,RouteToMarket,ElapsedDaysInSalesStage,SalesStageChangeCount,TotalDaysIdentifiedThroughClosing,TotalDaysIdentifiedThroughQualified,OpportunityAmountUSD,ClientSizeByRevenue,ClientSizeByEmployeeCount,RevenueFromClientPastTwoYears,CompetitorType,RatioDaysIdentifiedToTotalDays,RatioDaysValidatedToTotalDays,RatioDaysQualifiedToTotalDays,DealSizeCategory,OpportunityResult,PREDICT
0,8101406,5,2,4,1,43,1,0,0,0,1,1,0,2,0.000000,0.000000,0.000000,1,Loss,Loss
1,9793522,4,0,6,2,10,3,1,1,200000,1,1,0,2,0.000000,0.071429,0.928571,5,Loss,Loss
2,8529826,2,0,3,2,17,2,11,11,50000,1,1,0,2,0.000000,1.000000,0.000000,4,Loss,Loss
3,9778422,10,0,4,0,11,2,1,1,50000,1,1,0,2,0.000000,1.000000,0.000000,4,Loss,Loss
4,9869026,4,0,6,4,9,1,0,0,50000,1,1,0,2,0.000000,0.000000,0.000000,4,Loss,Loss
5,8507245,0,0,1,0,8,3,20,20,100000,1,1,0,2,0.284264,0.715736,0.000000,5,Loss,Loss
6,9550209,5,2,5,0,18,2,1,0,19600,1,1,3,2,0.000000,0.000000,0.000000,2,Won,Loss
7,7356420,3,0,2,2,49,2,22,22,40000,2,2,0,2,0.000000,1.000000,0.000000,3,Loss,Loss
8,7527295,5,2,5,2,63,2,0,0,40000,3,2,0,2,0.000000,0.000000,0.000000,3,Loss,Loss
9,8333531,2,0,4,0,16,2,19,19,40000,1,1,0,2,0.000000,1.000000,0.000000,3,Loss,Loss
10,9493456,8,2,1,0,10,2,12,12,214,1,1,0,2,0.000000,1.000000,0.000000,1,Loss,Loss
11,7791404,2,0,4,0,22,3,31,31,1000000,1,1,0,2,0.967427,0.032573,0.000000,7,Loss,Loss
12,7135527,3,0,5,2,76,3,3,3,1900,5,2,0,2,0.000000,0.031250,0.968750,1,Loss,Loss
13,8107741,4,0,3,2,16,5,25,25,98684,1,1,0,2,0.019841,0.000000,0.980159,4,Loss,Loss
14,6835113,10,0,1,0,65,7,25,25,200000,1,1,0,0,0.056000,0.544000,0.400000,5,Loss,Loss
15,8407841,5,2,5,2,0,9,28,26,73000,1,1,0,2,0.098940,0.003534,0.798587,4,Won,Loss
16,6858636,5,2,3,2,79,4,7,7,30000,4,2,0,2,0.000000,0.694444,0.305556,3,Won,Loss
17,7236000,5,2,1,0,65,2,10,10,60000,1,3,0,2,0.000000,1.000000,0.000000,4,Loss,Loss
18,8294760,8,2,4,0,35,2,1,1,200000,1,1,0,2,1.000000,0.000000,0.000000,5,Loss,Loss
19,7808184,5,2,1,2,16,3,25,25,10582,1,1,4,2,0.000000,1.000000,0.000000,2,Won,Loss
20,8008732,4,0,4,2,46,1,0,0,19972,1,1,0,2,0.000000,0.000000,0.000000,2,Won,Loss
21,6312407,8,2,5,2,44,3,68,68,50000,4,5,0,2,0.000000,0.002946,0.997054,4,Loss,Loss
22,8148869,2,0,4,0,9,5,24,18,110000,1,1,0,2,0.000000,0.260504,0.478992,5,Won,Loss
23,8022043,5,2,0,1,39,3,7,7,100000,1,1,4,2,0.529412,0.470588,0.000000,5,Loss,Loss
24,7974047,2,0,1,2,47,1,0,0,100000,1,1,0,2,0.000000,0.000000,0.000000,5,Loss,Loss
25,6806369,5,2,2,0,76,3,14,14,50000,2,1,0,2,0.363636,0.636364,0.000000,4,Loss,Loss
26,7234857,8,2,5,2,73,2,2,2,82260,1,4,0,2,0.000000,1.000000,0.000000,4,Won,Loss
27,6986368,8,2,0,0,49,4,35,35,180000,1,5,0,2,0.150142,0.399433,0.450425,5,Loss,Loss
28,7023920,7,0,1,2,83,1,0,0,11034,4,5,0,2,0.000000,0.000000,0.000000,2,Won,Loss
29,9473313,3,0,0,2,7,3,15,15,20000,1,1,0,2,0.000000,1.000000,0.000000,2,Loss,Loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23378,8223426,4,0,3,0,28,3,10,10,0,1,1,0,2,0.019231,0.980769,0.000000,1,Loss,Loss
23379,8215383,0,0,4,0,1,6,15,15,116261,1,1,0,2,0.617450,0.382550,0.000000,5,Loss,Loss
23380,7534604,4,0,2,2,41,7,7,1,10038,5,2,0,2,0.055556,0.013889,0.069444,2,Won,Loss
23381,7246228,7,0,4,2,61,3,14,14,7750,1,1,0,2,0.120567,0.879433,0.000000,1,Loss,Loss
23382,6673777,2,0,1,2,64,2,33,33,20000,1,3,0,1,0.000000,1.000000,0.000000,2,Loss,Loss
23383,6748393,3,0,2,2,57,2,37,37,56717,1,1,0,2,0.000000,1.000000,0.000000,4,Loss,Loss
23384,8257278,5,2,1,0,0,4,38,38,110000,1,1,0,0,0.000000,0.771883,0.228117,5,Loss,Loss
23385,7105808,5,2,3,2,48,5,32,32,30000,1,1,0,2,0.009434,0.691824,0.298742,3,Loss,Loss
23386,6438311,1,1,1,2,24,2,0,0,10392,5,1,0,2,0.000000,0.000000,0.000000,2,Won,Loss
23387,6905347,7,0,4,0,85,2,2,2,15000,1,2,0,2,0.000000,1.000000,0.000000,2,Loss,Loss
23388,7339448,0,0,0,0,40,3,31,31,200000,1,5,4,0,0.203822,0.796178,0.000000,5,Loss,Loss
23389,8100742,0,0,6,2,16,3,27,27,25000,1,1,0,2,0.000000,1.000000,0.000000,3,Loss,Loss
23390,7269442,2,0,6,2,44,2,30,30,15000,1,1,0,2,0.000000,1.000000,0.000000,2,Loss,Loss
23391,6820312,5,2,4,0,76,3,14,14,200000,5,1,0,2,0.021277,0.978723,0.000000,5,Loss,Loss
23392,6380425,6,2,4,0,81,2,28,28,95000,4,1,0,1,1.000000,0.000000,0.000000,4,Loss,Loss
23393,6979446,7,0,1,0,53,4,20,20,250000,5,5,3,2,0.000000,0.106061,0.893939,6,Loss,Loss
23394,6701063,3,0,6,2,86,3,10,10,25000,1,1,0,2,0.020000,0.980000,0.000000,3,Loss,Loss
23395,6646984,0,0,4,4,60,3,3,3,0,1,1,0,2,0.000000,1.000000,0.000000,1,Won,Loss
23396,9559064,5,2,4,0,12,2,6,6,17,1,1,0,2,1.000000,0.000000,0.000000,1,Won,Loss
23397,7387516,10,0,5,0,64,2,5,5,50000,1,1,0,2,0.000000,1.000000,0.000000,4,Loss,Loss
23398,7857002,4,0,4,4,48,2,3,3,25000,1,1,0,2,1.000000,0.000000,0.000000,3,Loss,Loss
23399,6745226,5,2,2,2,16,6,35,35,65000,1,1,0,2,0.000000,0.002865,0.997135,4,Won,Loss
23400,7791356,9,3,6,0,53,1,0,0,0,1,1,0,2,0.000000,0.000000,0.000000,1,Loss,Loss
23401,7312616,3,0,6,2,72,2,0,0,797860,1,1,0,2,0.000000,0.000000,0.000000,7,Loss,Loss
23402,6413581,8,2,4,2,24,3,7,7,23252,1,1,0,2,0.000000,1.000000,0.000000,2,Won,Loss
23403,7226889,2,0,6,2,63,3,13,13,100000,1,4,0,2,0.000000,0.007812,0.992188,5,Loss,Loss
23404,8026037,10,0,6,0,36,2,10,10,110000,1,1,0,2,1.000000,0.000000,0.000000,5,Loss,Loss
23405,6236095,7,0,5,0,89,3,26,26,10000,2,1,0,2,0.511719,0.488281,0.000000,2,Loss,Loss
23406,8516092,3,0,3,2,17,3,11,11,4000,1,1,0,1,0.000000,1.000000,0.000000,1,Loss,Loss
23407,7666872,0,0,0,0,52,2,6,6,50000,1,1,0,2,0.000000,1.000000,0.000000,4,Loss,Loss

In [26]:
finalResult[finalResult['PREDICT']=='Won']

,OpportunityNumber,SuppliesSubgroup,SuppliesGroup,Region,RouteToMarket,ElapsedDaysInSalesStage,SalesStageChangeCount,TotalDaysIdentifiedThroughClosing,TotalDaysIdentifiedThroughQualified,OpportunityAmountUSD,ClientSizeByRevenue,ClientSizeByEmployeeCount,RevenueFromClientPastTwoYears,CompetitorType,RatioDaysIdentifiedToTotalDays,RatioDaysValidatedToTotalDays,RatioDaysQualifiedToTotalDays,DealSizeCategory,OpportunityResult,PREDICT
2662,9877355,3,0,1,2,5,2,4,4,1248,1,1,0,0,1.000000,0.000000,0.000000,1,Won,Won
3046,7902106,7,0,5,0,29,2,0,0,12500,1,1,4,1,0.000000,0.000000,0.000000,2,Won,Won
9690,1724032,1,1,6,0,210,5,94,90,469000,1,1,0,1,0.073248,0.839703,0.040340,6,Won,Won
9732,9679646,7,0,5,0,1,2,14,0,15000,1,1,4,2,0.000000,0.000000,0.000000,2,Won,Won
10565,6321949,7,0,4,1,46,2,0,0,26874,1,1,0,2,0.000000,0.000000,0.000000,3,Won,Won
12180,8093335,0,0,4,0,37,2,7,0,12000,1,1,2,0,0.000000,0.000000,0.000000,2,Won,Won
13167,7055542,5,2,2,0,54,4,13,13,29500,1,1,3,2,0.843284,0.156716,0.000000,3,Won,Won
13751,7601063,8,2,4,4,51,3,1,1,0,1,1,0,1,0.000000,1.000000,0.000000,1,Won,Won
14817,7405917,7,0,4,0,68,1,0,0,57000,1,1,4,2,0.000000,0.000000,0.000000,4,Won,Won
15000,7885444,4,0,4,2,47,2,3,3,15501,1,1,0,1,0.000000,1.000000,0.000000,2,Won,Won
15869,9361151,7,0,5,0,16,2,10,10,14000,1,1,2,2,0.000000,0.000000,1.000000,2,Won,Won
17693,7884410,3,0,5,2,42,4,8,7,5000,1,1,0,0,0.000000,0.012821,0.858974,1,Won,Won
17886,8093335,0,0,4,0,37,2,7,0,12000,1,1,2,0,0.000000,0.000000,0.000000,2,Won,Won
18234,7405931,7,0,4,0,68,1,0,0,25095,1,1,0,2,0.000000,0.000000,0.000000,3,Won,Won
23085,8133081,8,2,4,0,42,1,0,0,11626,1,1,4,1,0.000000,0.000000,0.000000,2,Won,Won

In [27]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [ ]:
# recall 답지 기준 예측 보는 / precision 예측기준 답지 보는 / f1-score = recall*precision 2가지를 합쳐 보는

In [29]:
as_score = accuracy_score(finalResult.OpportunityResult,finalResult.PREDICT)

In [30]:
as_score

0.7705912508544087

In [31]:
clfc_report = classification_report(finalResult.OpportunityResult,finalResult.PREDICT)

In [32]:
print("result= \n",clfc_report)

result=
               precision    recall  f1-score   support

        Loss       0.77      1.00      0.87     18023
         Won       1.00      0.00      0.01      5385

    accuracy                           0.77     23408
   macro avg       0.89      0.50      0.44     23408
weighted avg       0.82      0.77      0.67     23408